name: Build and Deploy methodology
on:
  push:
   branches:
   - dev
   - prod
   paths:
    - 'carbon-registry-scrappers/**'
    #  - '.github/workflows/methodology-jobs.yaml'
env:
  GCP_PROJECT_ID: ${{vars.PROJECT_ID}}
  IMAGE_REGISTRY: asia.gcr.io
  IMAGE_NAME: acr_methodology-scraper
  IMAGE_NAME_TWO: methodology-scraper
  IMAGE_NAME_THREE: vcs_methodology-scraper
  REGION: asia-south1
jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure gcloud CLI
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.JSON_SOURCE_SERVICE_ACCOUNT }}
    - name: Build and push Docker images
      run: |
        gcloud auth configure-docker $IMAGE_REGISTRY
        cd carbon-registry-scrappers/acr_methodology_scrapper  && docker build -t $IMAGE_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME --build-arg GCP_PROJECT_ID="$GCP_PROJECT_ID"  .
        docker push $IMAGE_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME
    - name: Build and push Docker images
      run: |
        gcloud auth configure-docker $IMAGE_REGISTRY
        cd carbon-registry-scrappers/methdology_scrapper && docker build -t $IMAGE_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME_TWO --build-arg GCP_PROJECT_ID="$GCP_PROJECT_ID"  .
        docker push $IMAGE_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME_TWO
    - name: Build and push Docker images
      run: |
        gcloud auth configure-docker $IMAGE_REGISTRY
        cd carbon-registry-scrappers/vcs_methodology && docker build -t $IMAGE_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME_THREE --build-arg GCP_PROJECT_ID="$GCP_PROJECT_ID"  .
        docker push $IMAGE_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME_THREE

  build-and-deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    environment: prod
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure gcloud CLI
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.JSON_SOURCE_SERVICE_ACCOUNT }}
    - name: Build and push Docker images
      run: |
        gcloud auth configure-docker $IMAGE_REGISTRY
        cd carbon-registry-scrappers/acr_methodology_scrapper  && docker build -t $IMAGE_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME --build-arg GCP_PROJECT_ID="$GCP_PROJECT_ID"  .
        docker push $IMAGE_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME
    - name: Build and push Docker images
      run: |
        gcloud auth configure-docker $IMAGE_REGISTRY
        cd carbon-registry-scrappers/methdology_scrapper && docker build -t $IMAGE_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME_TWO --build-arg GCP_PROJECT_ID="$GCP_PROJECT_ID"  .
        docker push $IMAGE_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME_TWO
    - name: Build and push Docker images
      run: |
        gcloud auth configure-docker $IMAGE_REGISTRY
        cd carbon-registry-scrappers/vcs_methodology && docker build -t $IMAGE_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME_THREE --build-arg GCP_PROJECT_ID="$GCP_PROJECT_ID"  .
        docker push $IMAGE_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME_THREE

   
    # - name: deploy terraform
    #   run: |
    #     cd terraform
    #     terraform init 
    #     terraform plan
    #     terraform apply --auto-approve #
